create table "public"."Missed Calls" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "to_phone_number" text,
    "from_phone_number" text
);


CREATE UNIQUE INDEX "Missed Calls_pkey" ON public."Missed Calls" USING btree (id);

alter table "public"."Missed Calls" add constraint "Missed Calls_pkey" PRIMARY KEY using index "Missed Calls_pkey";

alter table "public"."Missed Calls" add constraint "Missed Calls_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "Users"(id) not valid;

alter table "public"."Missed Calls" validate constraint "Missed Calls_user_id_fkey";

grant delete on table "public"."Missed Calls" to "anon";

grant insert on table "public"."Missed Calls" to "anon";

grant references on table "public"."Missed Calls" to "anon";

grant select on table "public"."Missed Calls" to "anon";

grant trigger on table "public"."Missed Calls" to "anon";

grant truncate on table "public"."Missed Calls" to "anon";

grant update on table "public"."Missed Calls" to "anon";

grant delete on table "public"."Missed Calls" to "authenticated";

grant insert on table "public"."Missed Calls" to "authenticated";

grant references on table "public"."Missed Calls" to "authenticated";

grant select on table "public"."Missed Calls" to "authenticated";

grant trigger on table "public"."Missed Calls" to "authenticated";

grant truncate on table "public"."Missed Calls" to "authenticated";

grant update on table "public"."Missed Calls" to "authenticated";

grant delete on table "public"."Missed Calls" to "service_role";

grant insert on table "public"."Missed Calls" to "service_role";

grant references on table "public"."Missed Calls" to "service_role";

grant select on table "public"."Missed Calls" to "service_role";

grant trigger on table "public"."Missed Calls" to "service_role";

grant truncate on table "public"."Missed Calls" to "service_role";

grant update on table "public"."Missed Calls" to "service_role";


