create table "public"."Waitlist" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text,
    "email" text
);


CREATE UNIQUE INDEX "Waitlist_pkey" ON public."Waitlist" USING btree (id);

alter table "public"."Waitlist" add constraint "Waitlist_pkey" PRIMARY KEY using index "Waitlist_pkey";

grant delete on table "public"."Waitlist" to "anon";

grant insert on table "public"."Waitlist" to "anon";

grant references on table "public"."Waitlist" to "anon";

grant select on table "public"."Waitlist" to "anon";

grant trigger on table "public"."Waitlist" to "anon";

grant truncate on table "public"."Waitlist" to "anon";

grant update on table "public"."Waitlist" to "anon";

grant delete on table "public"."Waitlist" to "authenticated";

grant insert on table "public"."Waitlist" to "authenticated";

grant references on table "public"."Waitlist" to "authenticated";

grant select on table "public"."Waitlist" to "authenticated";

grant trigger on table "public"."Waitlist" to "authenticated";

grant truncate on table "public"."Waitlist" to "authenticated";

grant update on table "public"."Waitlist" to "authenticated";

grant delete on table "public"."Waitlist" to "service_role";

grant insert on table "public"."Waitlist" to "service_role";

grant references on table "public"."Waitlist" to "service_role";

grant select on table "public"."Waitlist" to "service_role";

grant trigger on table "public"."Waitlist" to "service_role";

grant truncate on table "public"."Waitlist" to "service_role";

grant update on table "public"."Waitlist" to "service_role";


